### ISSUE TITLE
Adapt readme for changed update procedure

### ISSUE THREAD

**Issue by joba-1** [ladral/qnap-nextcloud#7]
Hi ladral,

thanks for your yaml. Installation worked fine with one exception: I had to remove the content of the deploy: sections to make it compatible with containerstation 3.

And now that I wanted to do my first nextcloud update, I learned this is done different from your description since ~1/2 year. Maybe you want to adapt your readme?

There is no nextcloud update process to start anymore. If an update is required, the container will detect this and do it automatically.
Only problem is that you are not allowed to skip major versions. E.g. to go from 26 to 28 directly is not possible. 
So either update often or be prepared for some additional steps (cannot use latest label)

**Comment by ladral** [comment]
Hi joba-1

Thanks for the indication. I forgot to update the yaml and the readme. 

It is a pity that resource limits are no longer supported since Container Station 3. Especially since it is an official specification of docker-compose. I have already opened a ticket at Qnap. Unfortunately, they do not consider supporting official specifications as mandatory. If you want to set resource limits, you have to do it manually under the advanced settings.

I will update the readme accordingly.
